from sqlalchemy import Column, Table
from sqlalchemy.sql.sqltypes import INTEGER, String
from srback.db.db import meta, engine
users = Table('user', meta,
              Column('id', INTEGER(), primary_key=True),
              Column('name', String(255)),
              Column('pw', String(255)),
              Column('message', String(255)),
              Column('age', INTEGER()),
              Column('allergy', String(32)),
              Column('disease', String(32)),
              Column('alarmTime', String(32)),
              Column('alarmState', String(32)),
              )

alarms = Table('alarm', meta,
              Column('id', INTEGER(), primary_key=True),
              Column('userName', String(255)),
              Column('alarmState', String(255)),
              Column('recoMeal', String(255)),
              Column('resOfAi', String(255)),
              Column('chkEat', String(255)),
              Column('MLD', String(255)),
              Column('alarmImg', String(255)),
              Column('alarmTime', String(255)),
              Column('crtTime', String(255)),
              Column('chgTime', String(255)),
              Column('recoComment', String(2000)),
              Column('goodFB', String(2000)),
              Column('badFB', String(2000)),
              )

meals = Table('meal', meta,
              Column('id', INTEGER(), primary_key=True),
              Column('product_name', String(255)),
              Column('comment', String(2000)),
              Column('weight', String(255)),
              Column('discount_rate', INTEGER()),
              Column('discounted_price', INTEGER()),
              Column('original_price', INTEGER()),
              Column('calorie', INTEGER()),
              Column('milk_allergy', String(10)),
              Column('egg_allergy', String(10)),
              Column('peanut_allergy', String(10)),
              Column('shellfish_allergy', String(10)),
              Column('gluten_allergy', String(10)),
              Column('shrimp_allergy', String(10)),
              Column('peach_allergy', String(10)),
              Column('tomato_allergy', String(10)),
              Column('good_for_hypertension', String(10)),
              Column('good_for_diabetes', String(10)),
              Column('good_for_heart_disease', String(10)),
              Column('good_for_stroke', String(10)),
              Column('good_for_cancer', String(10)),
              Column('good_for_liver_disease', String(10)),
              Column('good_for_lung_disease', String(10)),
              Column('good_for_obesity_disease', String(10)),
              Column('img_url', String(2000)),
          )


meta.create_all(engine)